setwd("C:\\Users\\dave_\\Desktop\\DHDA\\SEMESTER2\\Data Analytics II\\Week 4")
install.packages("data.table")
install.packages("ggplot2")
install.packages("tidyverse")
install.packages("tidyr")
install.packages("plotly")
install.packages("Hmisc")
install.packages("sas7bdat")
install.packages("broom")
install.packages("esquisse")
install.packages("readxl")
install.packages("anytime")
install.packages("robustbase")
install.packages("gtsummary")
install.packages("rjson")
install.packages("jsonlite")


library(data.table)
library(sas7bdat)
library(readxl)
library(broom)
library(ggplot2)
library(tidyr)
library(anytime)
library(robustbase)
library(gtsummary)
library(rjson)

data <- read.sas7bdat('xtrsupmerged.sas7bdat')
names(data) = casefold(names(data))
names(data)

model <- lm(bonespacing ~ age, data = data)
summary(model)
confint(model)

cor(data$bonespacing, data$age, method='pearson', use='complete.obs')
#cor(data$bonespacing, data$age, method='spearman', use='complete.obs')

model2 = glm(data$bonespacing ~ data$age + data$bmi + data$previousfracture, 
             data = data, family='gaussian')
summary(model2)
confint(model2)